using KnowledgeBase.Application.Abstractions;
using KnowledgeBase.Contracts.Knowledge;
using KnowledgeBase.Domain.Entities;
using KnowledgeBase.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace KnowledgeBase.Infrastructure.Services;

public sealed class KnowledgeAssetService(KnowledgeDbContext db) : IKnowledgeAssetService
{
    public async Task<IReadOnlyList<TagDto>> GetTagsAsync(CancellationToken ct)=>await db.DocumentTags.AsNoTracking().OrderBy(x=>x.Name).Select(x=>new TagDto(x.Id,x.Name,x.Color)).ToListAsync(ct);
    public async Task<TagDto> SaveTagAsync(Guid? id,SaveTagRequest r,CancellationToken ct){DocumentTag x;if(id is null){x=new DocumentTag(r.Name,r.Color);db.DocumentTags.Add(x);}else{x=await db.DocumentTags.FirstAsync(a=>a.Id==id,ct);x.Update(r.Name,r.Color);}await db.SaveChangesAsync(ct);return new(x.Id,x.Name,x.Color);}
    public async Task<bool> DeleteTagAsync(Guid id,CancellationToken ct){var x=await db.DocumentTags.FirstOrDefaultAsync(a=>a.Id==id,ct);if(x is null)return false;db.DocumentTagLinks.RemoveRange(db.DocumentTagLinks.Where(a=>a.TagId==id));db.DocumentTags.Remove(x);await db.SaveChangesAsync(ct);return true;}
    public async Task SetDocumentTagsAsync(Guid documentId,IReadOnlyList<Guid> tagIds,CancellationToken ct){db.DocumentTagLinks.RemoveRange(db.DocumentTagLinks.Where(x=>x.DocumentId==documentId));foreach(var id in tagIds.Distinct())db.DocumentTagLinks.Add(new DocumentTagLink(documentId,id));await db.SaveChangesAsync(ct);}
    public async Task<IReadOnlyList<TagDto>> GetDocumentTagsAsync(Guid documentId,CancellationToken ct)=>await(from l in db.DocumentTagLinks join t in db.DocumentTags on l.TagId equals t.Id where l.DocumentId==documentId select new TagDto(t.Id,t.Name,t.Color)).ToListAsync(ct);
    public async Task<bool> ToggleFavoriteAsync(Guid userId,Guid documentId,CancellationToken ct){var x=await db.DocumentFavorites.FirstOrDefaultAsync(a=>a.UserId==userId&&a.DocumentId==documentId,ct);if(x is null){db.DocumentFavorites.Add(new DocumentFavorite(userId,documentId));await db.SaveChangesAsync(ct);return true;}db.DocumentFavorites.Remove(x);await db.SaveChangesAsync(ct);return false;}
    public async Task<IReadOnlyList<FavoriteDocumentDto>> GetFavoritesAsync(Guid userId,CancellationToken ct)=>await(from f in db.DocumentFavorites join d in db.Documents on f.DocumentId equals d.Id where f.UserId==userId orderby f.CreatedAt descending select new FavoriteDocumentDto(d.Id,d.Title,f.CreatedAt)).ToListAsync(ct);
    public async Task TrackRecentAsync(Guid userId,Guid documentId,CancellationToken ct){var x=await db.DocumentRecentViews.FirstOrDefaultAsync(a=>a.UserId==userId&&a.DocumentId==documentId,ct);if(x is null)db.DocumentRecentViews.Add(new DocumentRecentView(userId,documentId));else x.Touch();await db.SaveChangesAsync(ct);}
    public async Task<IReadOnlyList<RecentDocumentDto>> GetRecentAsync(Guid userId,int take,CancellationToken ct)=>await(from r in db.DocumentRecentViews join d in db.Documents on r.DocumentId equals d.Id where r.UserId==userId orderby r.LastViewedAt descending select new RecentDocumentDto(d.Id,d.Title,r.LastViewedAt,r.ViewCount)).Take(Math.Clamp(take,1,100)).ToListAsync(ct);
    public async Task<VersionDto?> CreateVersionAsync(Guid documentId,Guid? editorId,string changeNote,CancellationToken ct){var d=await db.Documents.FirstOrDefaultAsync(x=>x.Id==documentId,ct);if(d is null)return null;var markdown=await db.DocumentContents.Where(x=>x.DocumentId==documentId).Select(x=>x.Markdown).FirstOrDefaultAsync(ct)??string.Empty;var no=(await db.DocumentVersions.Where(x=>x.DocumentId==documentId).MaxAsync(x=>(int?)x.VersionNumber,ct)??0)+1;var v=new DocumentVersion(documentId,no,d.Title,d.Slug,markdown,editorId,changeNote);db.DocumentVersions.Add(v);await db.SaveChangesAsync(ct);return new(v.Id,v.DocumentId,v.VersionNumber,v.Title,v.ChangeNote,v.CreatedAt);}
    public async Task<IReadOnlyList<VersionDto>> GetVersionsAsync(Guid documentId,CancellationToken ct)=>await db.DocumentVersions.AsNoTracking().Where(x=>x.DocumentId==documentId).OrderByDescending(x=>x.VersionNumber).Select(x=>new VersionDto(x.Id,x.DocumentId,x.VersionNumber,x.Title,x.ChangeNote,x.CreatedAt)).ToListAsync(ct);
    public async Task<VersionDetailDto?> GetVersionAsync(Guid versionId,CancellationToken ct)=>await db.DocumentVersions.AsNoTracking().Where(x=>x.Id==versionId).Select(x=>new VersionDetailDto(x.Id,x.DocumentId,x.VersionNumber,x.Title,x.Slug,x.Markdown,x.ChangeNote,x.CreatedAt)).FirstOrDefaultAsync(ct);
    public async Task<bool> RestoreVersionAsync(Guid versionId,Guid? editorId,CancellationToken ct){var v=await db.DocumentVersions.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==versionId,ct);if(v is null)return false;var d=await db.Documents.FirstOrDefaultAsync(x=>x.Id==v.DocumentId,ct);if(d is null)return false;var content=await db.DocumentContents.FirstOrDefaultAsync(x=>x.DocumentId==d.Id,ct);if(content is null)return false;await CreateVersionAsync(d.Id,editorId,$"恢复前自动备份 v{v.VersionNumber}",ct);d.UpdateMetadata(v.Title,v.Slug,d.ParentId);content.Update(v.Markdown);await db.SaveChangesAsync(ct);return true;}
    public async Task<IReadOnlyList<SearchResultDto>> SearchAsync(string keyword,Guid? knowledgeBaseId,int take,CancellationToken ct){keyword=(keyword??string.Empty).Trim();if(keyword.Length==0)return[];var q=from d in db.Documents.AsNoTracking() join c in db.DocumentContents.AsNoTracking() on d.Id equals c.DocumentId where d.Title.Contains(keyword)||c.Markdown.Contains(keyword) select new{d,c};if(knowledgeBaseId.HasValue)q=q.Where(x=>x.d.KnowledgeBaseId==knowledgeBaseId.Value);var rows=await q.OrderByDescending(x=>x.d.UpdatedAt).Take(Math.Clamp(take,1,100)).Select(x=>new{x.d.Id,x.d.KnowledgeBaseId,x.d.Title,x.c.Markdown,x.d.UpdatedAt}).ToListAsync(ct);return rows.Select(x=>new SearchResultDto(x.Id,x.KnowledgeBaseId,x.Title,BuildSnippet(x.Markdown,keyword),x.UpdatedAt)).ToList();}
    private static string BuildSnippet(string text,string keyword){if(string.IsNullOrEmpty(text))return string.Empty;var i=text.IndexOf(keyword,StringComparison.OrdinalIgnoreCase);if(i<0)return text[..Math.Min(text.Length,180)];var start=Math.Max(0,i-70);var len=Math.Min(text.Length-start,180);return text.Substring(start,len).Replace("\r"," ").Replace("\n"," ");}
}
