using System.Security.Cryptography;
using KnowledgeBase.Application.Abstractions;
using KnowledgeBase.Contracts.System;
using KnowledgeBase.Domain.Entities;
using KnowledgeBase.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace KnowledgeBase.Infrastructure.Services;

public sealed class SystemManagementService(KnowledgeDbContext db):ISystemManagementService
{
    public async Task<IReadOnlyList<UserDto>> GetUsersAsync(CancellationToken ct){var users=await db.Users.AsNoTracking().OrderBy(x=>x.UserName).ToListAsync(ct);var links=await db.UserRoles.AsNoTracking().ToListAsync(ct);var roles=await db.Roles.AsNoTracking().ToDictionaryAsync(x=>x.Id,ct);return users.Select(u=>{var userRoleIds=links.Where(x=>x.UserId==u.Id).Select(x=>x.RoleId).ToList();var roleNames=userRoleIds.Where(roles.ContainsKey).Select(x=>roles[x].Name).ToList();return new UserDto(u.Id,u.UserName,u.DisplayName,u.Enabled,userRoleIds,roleNames,u.CreatedAt);}).ToList();}
    public async Task<UserDto> SaveUserAsync(Guid? id,SaveUserRequest r,CancellationToken ct){SysUser u;if(id is null){var(h,s)=Hash(string.IsNullOrWhiteSpace(r.Password)?"ChangeMe123!":r.Password);u=new SysUser(r.UserName,r.DisplayName,h,s);db.Users.Add(u);}else{u=await db.Users.FirstAsync(x=>x.Id==id,ct);u.Update(r.DisplayName,r.Enabled);if(!string.IsNullOrWhiteSpace(r.Password)){var(h,s)=Hash(r.Password);u.ChangePassword(h,s);}db.UserRoles.RemoveRange(db.UserRoles.Where(x=>x.UserId==u.Id));}foreach(var roleId in r.RoleIds.Distinct())db.UserRoles.Add(new SysUserRole(u.Id,roleId));await db.SaveChangesAsync(ct);return (await GetUsersAsync(ct)).First(x=>x.Id==u.Id);}
    public async Task<bool> DeleteUserAsync(Guid id,CancellationToken ct){var u=await db.Users.FirstOrDefaultAsync(x=>x.Id==id,ct);if(u is null||u.UserName=="admin")return false;db.UserRoles.RemoveRange(db.UserRoles.Where(x=>x.UserId==id));db.Users.Remove(u);await db.SaveChangesAsync(ct);return true;}
    public async Task<IReadOnlyList<RoleDto>> GetRolesAsync(CancellationToken ct){var roles=await db.Roles.AsNoTracking().OrderBy(x=>x.Name).ToListAsync(ct);var links=await db.RoleMenus.AsNoTracking().ToListAsync(ct);return roles.Select(x=>new RoleDto(x.Id,x.Code,x.Name,x.Enabled,links.Where(m=>m.RoleId==x.Id).Select(m=>m.MenuId).ToList())).ToList();}
    public async Task<RoleDto> SaveRoleAsync(Guid? id,SaveRoleRequest r,CancellationToken ct){SysRole role;if(id is null){role=new SysRole(r.Code,r.Name);db.Roles.Add(role);}else{role=await db.Roles.FirstAsync(x=>x.Id==id,ct);role.Update(r.Code,r.Name,r.Enabled);db.RoleMenus.RemoveRange(db.RoleMenus.Where(x=>x.RoleId==role.Id));}foreach(var menuId in r.MenuIds.Distinct())db.RoleMenus.Add(new SysRoleMenu(role.Id,menuId));await db.SaveChangesAsync(ct);return (await GetRolesAsync(ct)).First(x=>x.Id==role.Id);}
    public async Task<bool> DeleteRoleAsync(Guid id,CancellationToken ct){var r=await db.Roles.FirstOrDefaultAsync(x=>x.Id==id,ct);if(r is null||r.Code=="SUPER_ADMIN")return false;db.UserRoles.RemoveRange(db.UserRoles.Where(x=>x.RoleId==id));db.RoleMenus.RemoveRange(db.RoleMenus.Where(x=>x.RoleId==id));db.Roles.Remove(r);await db.SaveChangesAsync(ct);return true;}
    public async Task<IReadOnlyList<TreeNodeDto>> GetDepartmentsAsync(CancellationToken ct)=>await db.Departments.AsNoTracking().OrderBy(x=>x.Sort).Select(x=>new TreeNodeDto(x.Id,x.ParentId,x.Name,null,x.Sort,x.Enabled)).ToListAsync(ct);
    public async Task<TreeNodeDto> SaveDepartmentAsync(Guid? id,SaveDepartmentRequest r,CancellationToken ct){SysDepartment x;if(id is null){x=new SysDepartment(r.Name,r.ParentId,r.Sort);db.Departments.Add(x);}else{x=await db.Departments.FirstAsync(a=>a.Id==id,ct);x.Update(r.Name,r.ParentId,r.Sort,r.Enabled);}await db.SaveChangesAsync(ct);return new(x.Id,x.ParentId,x.Name,null,x.Sort,x.Enabled);}
    public async Task<bool> DeleteDepartmentAsync(Guid id,CancellationToken ct)=>await DeleteNode(db.Departments,id,ct);
    public async Task<IReadOnlyList<TreeNodeDto>> GetOrganizationsAsync(CancellationToken ct)=>await db.Organizations.AsNoTracking().OrderBy(x=>x.Sort).Select(x=>new TreeNodeDto(x.Id,x.ParentId,x.Name,x.Code,x.Sort,x.Enabled)).ToListAsync(ct);
    public async Task<TreeNodeDto> SaveOrganizationAsync(Guid? id,SaveOrganizationRequest r,CancellationToken ct){SysOrganization x;if(id is null){x=new SysOrganization(r.Name,r.Code,r.ParentId);db.Organizations.Add(x);}else{x=await db.Organizations.FirstAsync(a=>a.Id==id,ct);}x.Update(r.Name,r.Code,r.ParentId,r.Sort,r.Enabled);await db.SaveChangesAsync(ct);return new(x.Id,x.ParentId,x.Name,x.Code,x.Sort,x.Enabled);}
    public async Task<bool> DeleteOrganizationAsync(Guid id,CancellationToken ct)=>await DeleteNode(db.Organizations,id,ct);
    public async Task<IReadOnlyList<MenuDto>> GetMenusAsync(CancellationToken ct)=>await db.Menus.AsNoTracking().OrderBy(x=>x.Sort).Select(x=>new MenuDto(x.Id,x.ParentId,x.Name,x.Path,x.Permission,x.Type,x.Icon,x.Sort,x.Enabled)).ToListAsync(ct);
    public async Task<MenuDto> SaveMenuAsync(Guid? id,SaveMenuRequest r,CancellationToken ct){SysMenu x;if(id is null){x=new SysMenu(r.Name,r.Path,r.Permission,r.ParentId,r.Sort);db.Menus.Add(x);}else x=await db.Menus.FirstAsync(a=>a.Id==id,ct);x.Update(r.Name,r.Path,r.Permission,r.Type,r.Icon,r.ParentId,r.Sort,r.Enabled);await db.SaveChangesAsync(ct);return new(x.Id,x.ParentId,x.Name,x.Path,x.Permission,x.Type,x.Icon,x.Sort,x.Enabled);}
    public async Task<bool> DeleteMenuAsync(Guid id,CancellationToken ct){var x=await db.Menus.FirstOrDefaultAsync(a=>a.Id==id,ct);if(x is null)return false;db.RoleMenus.RemoveRange(db.RoleMenus.Where(a=>a.MenuId==id));db.Menus.Remove(x);await db.SaveChangesAsync(ct);return true;}
    public async Task<PermissionProfileDto> GetPermissionProfileAsync(Guid userId,CancellationToken ct){var roleIds=await db.UserRoles.Where(x=>x.UserId==userId).Select(x=>x.RoleId).ToListAsync(ct);var roles=await db.Roles.Where(x=>roleIds.Contains(x.Id)&&x.Enabled).Select(x=>x.Code).ToListAsync(ct);if(roles.Contains("SUPER_ADMIN")){var all=await GetMenusAsync(ct);return new(roles,all.Where(x=>!string.IsNullOrWhiteSpace(x.Permission)).Select(x=>x.Permission).Distinct().ToList(),all);}var menuIds=await db.RoleMenus.Where(x=>roleIds.Contains(x.RoleId)).Select(x=>x.MenuId).Distinct().ToListAsync(ct);var menus=(await GetMenusAsync(ct)).Where(x=>menuIds.Contains(x.Id)&&x.Enabled).ToList();return new(roles,menus.Where(x=>!string.IsNullOrWhiteSpace(x.Permission)).Select(x=>x.Permission).Distinct().ToList(),menus);}
    public async Task<bool> ChangePasswordAsync(Guid userId,ChangePasswordRequest r,CancellationToken ct){var u=await db.Users.FirstOrDefaultAsync(x=>x.Id==userId,ct);if(u is null||!Verify(r.OldPassword,u.PasswordHash,u.PasswordSalt))return false;var(h,s)=Hash(r.NewPassword);u.ChangePassword(h,s);await db.SaveChangesAsync(ct);return true;}
    public async Task<IReadOnlyList<AuditLogDto>> GetAuditLogsAsync(int take,CancellationToken ct)=>await db.AuditLogs.AsNoTracking().OrderByDescending(x=>x.CreatedAt).Take(Math.Clamp(take,1,500)).Select(x=>new AuditLogDto(x.Id,x.Category,x.Action,x.UserName,x.Target,x.IpAddress,x.Success,x.Message,x.CreatedAt)).ToListAsync(ct);
    private async Task<bool> DeleteNode<T>(DbSet<T> set,Guid id,CancellationToken ct) where T:class{var x=await set.FindAsync([id],ct);if(x is null)return false;set.Remove(x);await db.SaveChangesAsync(ct);return true;}
    private static (string,string) Hash(string p){var s=RandomNumberGenerator.GetBytes(16);var h=Rfc2898DeriveBytes.Pbkdf2(p,s,120000,HashAlgorithmName.SHA256,32);return(Convert.ToBase64String(h),Convert.ToBase64String(s));}
    private static bool Verify(string p,string h,string s){var a=Rfc2898DeriveBytes.Pbkdf2(p,Convert.FromBase64String(s),120000,HashAlgorithmName.SHA256,32);return CryptographicOperations.FixedTimeEquals(a,Convert.FromBase64String(h));}
}
