<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../KnowledgeBase.Application/KnowledgeBase.Application.csproj" />
    <ProjectReference Include="../KnowledgeBase.Infrastructure/KnowledgeBase.Infrastructure.csproj" />
    <ProjectReference Include="../KnowledgeBase.Contracts/KnowledgeBase.Contracts.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>
</Project>
