<script setup lang="ts">
import { computed, nextTick, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowLeft, FilePlus2, History, Paperclip, Save, Star, Tags, Trash2 } from 'lucide-vue-next'
import { http } from '../api/http'

const route = useRoute(); const router = useRouter(); const knowledgeBaseId = String(route.params.id)
const knowledgeBase = ref<any>(null); const docs = ref<any[]>([]); const selectedId = ref<string>(''); const saving = ref(false)
const editor = reactive({ id:'', parentId:null as string|null, title:'', slug:'', markdown:'' })
const versions=ref<any[]>([]),allTags=ref<any[]>([]),tagIds=ref<string[]>([]),attachments=ref<any[]>([]),metaDrawer=ref(''),favorite=ref(false)
const fileInput=ref<HTMLInputElement|null>(null)
const treeData = computed(() => { const map = new Map<string, any>(); const roots:any[]=[]; docs.value.forEach(d=>map.set(d.id,{...d,label:d.title,children:[]})); map.forEach(n=>{ if(n.parentId && map.has(n.parentId)) map.get(n.parentId).children.push(n); else roots.push(n) }); return roots })

async function load(){ knowledgeBase.value=(await http.get(`/knowledge-bases/${knowledgeBaseId}`)).data; docs.value=(await http.get('/documents',{params:{knowledgeBaseId}})).data }
async function loadMeta(){if(!editor.id)return;const [vs,tags,all,files,favs]=await Promise.all([http.get(`/knowledge-assets/documents/${editor.id}/versions`),http.get(`/knowledge-assets/documents/${editor.id}/tags`),http.get('/knowledge-assets/tags'),http.get(`/attachments/document/${editor.id}`),http.get('/knowledge-assets/favorites')]);versions.value=vs.data;tagIds.value=tags.data.map((x:any)=>x.id);allTags.value=all.data;attachments.value=files.data;favorite.value=favs.data.some((x:any)=>x.documentId===editor.id)}
async function select(node:any){ selectedId.value=node.id; const {data}=await http.get(`/documents/${node.id}`); Object.assign(editor,{id:data.id,parentId:data.parentId,title:data.title,slug:data.slug,markdown:data.markdown});await http.post(`/knowledge-assets/documents/${node.id}/recent`);await loadMeta();await router.replace({query:{...route.query,document:node.id}}) }
function createDoc(){ selectedId.value=''; Object.assign(editor,{id:'',parentId:null,title:'未命名文档',slug:`doc-${Date.now()}`,markdown:'# 未命名文档\n\n开始记录知识内容。'});versions.value=[];tagIds.value=[];attachments.value=[];favorite.value=false }
function createChild(){ const parent=editor.id||null; Object.assign(editor,{id:'',parentId:parent,title:'新建子文档',slug:`doc-${Date.now()}`,markdown:'# 新建子文档\n'}) }
async function save(){ if(!editor.title.trim()) return ElMessage.warning('请输入文档标题'); saving.value=true; try { if(editor.id){await http.post(`/knowledge-assets/documents/${editor.id}/versions`,{changeNote:'编辑前自动快照'}); const {data}=await http.put(`/documents/${editor.id}`,{parentId:editor.parentId,title:editor.title,slug:editor.slug,markdown:editor.markdown}); editor.id=data.id } else { const {data}=await http.post('/documents',{knowledgeBaseId,parentId:editor.parentId,title:editor.title,slug:editor.slug,markdown:editor.markdown}); editor.id=data.id } ElMessage.success('文档已保存'); await load(); selectedId.value=editor.id;await loadMeta();await router.replace({query:{...route.query,document:editor.id}}) } finally { saving.value=false } }
async function remove(){ if(!editor.id)return; await ElMessageBox.confirm(`确认删除“${editor.title}”？`,'删除文档',{type:'warning'}); await http.delete(`/documents/${editor.id}`); Object.assign(editor,{id:'',parentId:null,title:'',slug:'',markdown:''}); selectedId.value=''; await load() }
async function toggleFavorite(){if(!editor.id)return;const {data}=await http.post(`/knowledge-assets/documents/${editor.id}/favorite`);favorite.value=data.favorite;ElMessage.success(favorite.value?'已收藏':'已取消收藏')}
async function saveTags(){if(!editor.id)return;await http.put(`/knowledge-assets/documents/${editor.id}/tags`,tagIds.value);ElMessage.success('标签已更新')}
async function createSnapshot(){if(!editor.id)return;const note=prompt('版本说明','手动快照')||'手动快照';await http.post(`/knowledge-assets/documents/${editor.id}/versions`,{changeNote:note});await loadMeta();ElMessage.success('版本快照已创建')}
async function restoreVersion(v:any){await ElMessageBox.confirm(`确认恢复到 v${v.versionNumber}？当前版本会自动备份。`,'恢复版本',{type:'warning'});await http.post(`/knowledge-assets/versions/${v.id}/restore`);await select({id:editor.id});ElMessage.success('版本已恢复')}
function chooseFile(){fileInput.value?.click()}
async function uploadFile(e:Event){const input=e.target as HTMLInputElement;const file=input.files?.[0];if(!file||!editor.id)return;const form=new FormData();form.append('file',file);await http.post(`/attachments/document/${editor.id}`,form,{headers:{'Content-Type':'multipart/form-data'}});input.value='';await loadMeta();ElMessage.success('附件已上传')}
async function downloadAttachment(a:any){const {data}=await http.get(a.downloadUrl,{responseType:'blob'});const url=URL.createObjectURL(data);const link=document.createElement('a');link.href=url;link.download=a.fileName;link.click();URL.revokeObjectURL(url)}
async function deleteAttachment(a:any){await ElMessageBox.confirm(`删除附件“${a.fileName}”？`,'删除附件',{type:'warning'});await http.delete(`/attachments/${a.id}`);await loadMeta()}
async function openMeta(name:string){metaDrawer.value=name;if(editor.id)await loadMeta()}

onMounted(async()=>{await load();const target=String(route.query.document||'');if(target&&docs.value.some(x=>x.id===target)){await nextTick();await select({id:target})}})
</script>
<template><section class="workspace-page"><header class="workspace-head"><button @click="router.push('/knowledge-bases')"><ArrowLeft :size="16"/>返回</button><div><strong>{{ knowledgeBase?.name || '知识库' }}</strong><span>{{ knowledgeBase?.description }}</span></div><div class="workspace-actions"><button @click="createDoc"><FilePlus2 :size="15"/>新建文档</button><button :disabled="!editor.id" @click="createChild">新建子文档</button><button :disabled="!editor.id" @click="toggleFavorite"><Star :size="15" :fill="favorite?'currentColor':'none'"/>{{favorite?'已收藏':'收藏'}}</button><button :disabled="!editor.id" @click="openMeta('versions')"><History :size="15"/>版本</button><button :disabled="!editor.id" @click="openMeta('tags')"><Tags :size="15"/>标签</button><button :disabled="!editor.id" @click="openMeta('attachments')"><Paperclip :size="15"/>附件</button><button class="primary" :disabled="!editor.title" @click="save"><Save :size="15"/>{{saving?'保存中':'保存'}}</button><button class="danger-text" :disabled="!editor.id" @click="remove"><Trash2 :size="15"/>删除</button></div></header><div class="workspace-body"><aside class="doc-tree"><div class="tree-title">文档目录 <span>{{docs.length}}</span></div><el-tree :data="treeData" node-key="id" :current-node-key="selectedId" highlight-current default-expand-all @node-click="select"/><div v-if="!docs.length" class="tree-empty">暂无文档</div></aside><main class="editor-pane"><div v-if="editor.title" class="editor-shell"><input v-model="editor.title" class="title-input"/><div class="meta-line"><span>Slug</span><input v-model="editor.slug"/></div><div class="editor-grid"><textarea v-model="editor.markdown" spellcheck="false"/><div class="preview"><div class="preview-label">PREVIEW</div><pre>{{editor.markdown}}</pre></div></div></div><div v-else class="editor-empty"><strong>选择或创建一篇文档</strong><p>正文仅在打开文档时加载，不随目录一次性返回。</p><button class="primary" @click="createDoc">创建第一篇文档</button></div></main></div>
<el-drawer v-model="metaDrawer" :title="metaDrawer==='versions'?'版本历史':metaDrawer==='tags'?'文档标签':'附件'" size="420px" @close="metaDrawer=''">
<div v-if="metaDrawer==='versions'"><el-button type="primary" @click="createSnapshot">创建快照</el-button><div class="meta-list" v-for="v in versions" :key="v.id"><div><strong>v{{v.versionNumber}} · {{v.title}}</strong><small>{{v.changeNote||'无说明'}} · {{v.createdAt}}</small></div><el-button link type="primary" @click="restoreVersion(v)">恢复</el-button></div></div>
<div v-if="metaDrawer==='tags'"><el-select v-model="tagIds" multiple filterable style="width:100%" placeholder="选择标签"><el-option v-for="t in allTags" :key="t.id" :label="t.name" :value="t.id"/></el-select><el-button type="primary" style="margin-top:14px" @click="saveTags">保存标签</el-button></div>
<div v-if="metaDrawer==='attachments'"><input ref="fileInput" type="file" hidden @change="uploadFile"/><el-button type="primary" @click="chooseFile">上传附件</el-button><div class="meta-list" v-for="a in attachments" :key="a.id"><div><strong>{{a.fileName}}</strong><small>{{Math.ceil(a.size/1024)}} KB · {{a.createdAt}}</small></div><span><el-button link type="primary" @click="downloadAttachment(a)">下载</el-button><el-button link type="danger" @click="deleteAttachment(a)">删除</el-button></span></div></div>
</el-drawer></section></template>
<style scoped>
.workspace-page{height:calc(100vh - 58px);display:flex;flex-direction:column}.workspace-head{height:72px;border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 22px;gap:18px}.workspace-head>button,.workspace-actions button{height:32px;border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:6px;display:flex;align-items:center;gap:6px;padding:0 10px}.workspace-head>div:nth-child(2){min-width:0}.workspace-head strong{display:block;font-size:14px}.workspace-head span{display:block;font-size:10px;color:var(--muted);margin-top:4px}.workspace-actions{margin-left:auto;display:flex;gap:7px;flex-wrap:wrap}.workspace-body{min-height:0;flex:1;display:grid;grid-template-columns:260px 1fr}.doc-tree{border-right:1px solid var(--border);padding:14px;background:var(--sidebar)}.tree-title{font-size:11px;color:var(--muted);padding:4px 8px 12px}.tree-title span{float:right}.tree-empty{font-size:11px;color:var(--muted);padding:20px 8px}.editor-pane{min-width:0;overflow:auto;background:var(--bg)}.editor-shell{height:100%;display:flex;flex-direction:column;padding:20px 24px}.title-input{font-size:25px;font-weight:650;background:transparent;border:0;color:var(--text);outline:none;padding:8px 0}.meta-line{display:flex;align-items:center;gap:10px;font-size:10px;color:var(--muted);margin:3px 0 14px}.meta-line input{width:260px;background:var(--surface);border:1px solid var(--border);color:var(--text);border-radius:5px;height:27px;padding:0 8px}.editor-grid{min-height:0;flex:1;display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--border);border-radius:8px;overflow:hidden}.editor-grid textarea{resize:none;border:0;border-right:1px solid var(--border);outline:none;background:var(--surface);color:var(--text);padding:18px;font:13px/1.8 Consolas,monospace}.preview{padding:18px;overflow:auto;background:var(--surface-2)}.preview-label{font-size:9px;letter-spacing:.15em;color:var(--muted);margin-bottom:12px}.preview pre{white-space:pre-wrap;font:13px/1.8 inherit;color:var(--text)}.editor-empty{height:100%;display:grid;place-items:center;align-content:center;text-align:center}.editor-empty strong{font-size:17px}.editor-empty p{color:var(--muted);font-size:12px}.editor-empty button{height:34px;border-radius:6px;padding:0 13px}.danger-text{color:#e56b6b!important}.meta-list{display:flex;align-items:center;justify-content:space-between;padding:14px 0;border-bottom:1px solid var(--border);gap:12px}.meta-list strong{display:block;font-size:13px}.meta-list small{display:block;color:var(--muted);font-size:11px;margin-top:5px}@media(max-width:1100px){.workspace-head{height:auto;min-height:72px;padding-top:10px;padding-bottom:10px}.workspace-body{grid-template-columns:220px 1fr}}@media(max-width:900px){.workspace-body{grid-template-columns:190px 1fr}.editor-grid{grid-template-columns:1fr}.preview{display:none}}
</style>
