<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowLeft, FilePlus2, Save, Trash2 } from 'lucide-vue-next'
import { http } from '../api/http'

const route = useRoute(); const router = useRouter(); const knowledgeBaseId = String(route.params.id)
const knowledgeBase = ref<any>(null); const docs = ref<any[]>([]); const selectedId = ref<string>(''); const saving = ref(false)
const editor = reactive({ id:'', parentId:null as string|null, title:'', slug:'', markdown:'' })
const treeData = computed(() => { const map = new Map<string, any>(); const roots:any[]=[]; docs.value.forEach(d=>map.set(d.id,{...d,label:d.title,children:[]})); map.forEach(n=>{ if(n.parentId && map.has(n.parentId)) map.get(n.parentId).children.push(n); else roots.push(n) }); return roots })
async function load(){ knowledgeBase.value=(await http.get(`/knowledge-bases/${knowledgeBaseId}`)).data; docs.value=(await http.get('/documents',{params:{knowledgeBaseId}})).data }
async function select(node:any){ selectedId.value=node.id; const {data}=await http.get(`/documents/${node.id}`); Object.assign(editor,{id:data.id,parentId:data.parentId,title:data.title,slug:data.slug,markdown:data.markdown}) }
function createDoc(){ selectedId.value=''; Object.assign(editor,{id:'',parentId:null,title:'未命名文档',slug:`doc-${Date.now()}`,markdown:'# 未命名文档\n\n开始记录知识内容。'}) }
function createChild(){ const parent=editor.id||null; Object.assign(editor,{id:'',parentId:parent,title:'新建子文档',slug:`doc-${Date.now()}`,markdown:'# 新建子文档\n'}) }
async function save(){ if(!editor.title.trim()) return ElMessage.warning('请输入文档标题'); saving.value=true; try { if(editor.id){ const {data}=await http.put(`/documents/${editor.id}`,{parentId:editor.parentId,title:editor.title,slug:editor.slug,markdown:editor.markdown}); editor.id=data.id } else { const {data}=await http.post('/documents',{knowledgeBaseId,parentId:editor.parentId,title:editor.title,slug:editor.slug,markdown:editor.markdown}); editor.id=data.id } ElMessage.success('文档已保存'); await load(); selectedId.value=editor.id } finally { saving.value=false } }
async function remove(){ if(!editor.id)return; await ElMessageBox.confirm(`确认删除“${editor.title}”？`,'删除文档',{type:'warning'}); await http.delete(`/documents/${editor.id}`); Object.assign(editor,{id:'',parentId:null,title:'',slug:'',markdown:''}); selectedId.value=''; await load() }
onMounted(load)
</script>
<template><section class="workspace-page"><header class="workspace-head"><button @click="router.push('/knowledge-bases')"><ArrowLeft :size="16"/>返回</button><div><strong>{{ knowledgeBase?.name || '知识库' }}</strong><span>{{ knowledgeBase?.description }}</span></div><div class="workspace-actions"><button @click="createDoc"><FilePlus2 :size="15"/>新建文档</button><button :disabled="!editor.id" @click="createChild">新建子文档</button><button class="primary" :disabled="!editor.title" @click="save"><Save :size="15"/>{{saving?'保存中':'保存'}}</button><button class="danger-text" :disabled="!editor.id" @click="remove"><Trash2 :size="15"/>删除</button></div></header><div class="workspace-body"><aside class="doc-tree"><div class="tree-title">文档目录 <span>{{docs.length}}</span></div><el-tree :data="treeData" node-key="id" :current-node-key="selectedId" highlight-current default-expand-all @node-click="select"/><div v-if="!docs.length" class="tree-empty">暂无文档</div></aside><main class="editor-pane"><div v-if="editor.title" class="editor-shell"><input v-model="editor.title" class="title-input"/><div class="meta-line"><span>Slug</span><input v-model="editor.slug"/></div><div class="editor-grid"><textarea v-model="editor.markdown" spellcheck="false"/><div class="preview"><div class="preview-label">PREVIEW</div><pre>{{editor.markdown}}</pre></div></div></div><div v-else class="editor-empty"><strong>选择或创建一篇文档</strong><p>正文仅在打开文档时加载，不随目录一次性返回。</p><button class="primary" @click="createDoc">创建第一篇文档</button></div></main></div></section></template>
<style scoped>
.workspace-page{height:calc(100vh - 58px);display:flex;flex-direction:column}.workspace-head{height:72px;border-bottom:1px solid var(--border);display:flex;align-items:center;padding:0 22px;gap:18px}.workspace-head>button,.workspace-actions button{height:32px;border:1px solid var(--border);background:var(--surface);color:var(--text);border-radius:6px;display:flex;align-items:center;gap:6px;padding:0 10px}.workspace-head>div:nth-child(2){min-width:0}.workspace-head strong{display:block;font-size:14px}.workspace-head span{display:block;font-size:10px;color:var(--muted);margin-top:4px}.workspace-actions{margin-left:auto;display:flex;gap:7px}.workspace-body{min-height:0;flex:1;display:grid;grid-template-columns:260px 1fr}.doc-tree{border-right:1px solid var(--border);padding:14px;background:var(--sidebar)}.tree-title{font-size:11px;color:var(--muted);padding:4px 8px 12px}.tree-title span{float:right}.tree-empty{font-size:11px;color:var(--muted);padding:20px 8px}.editor-pane{min-width:0;overflow:auto;background:var(--bg)}.editor-shell{height:100%;display:flex;flex-direction:column;padding:20px 24px}.title-input{font-size:25px;font-weight:650;background:transparent;border:0;color:var(--text);outline:none;padding:8px 0}.meta-line{display:flex;align-items:center;gap:10px;font-size:10px;color:var(--muted);margin:3px 0 14px}.meta-line input{width:260px;background:var(--surface);border:1px solid var(--border);color:var(--text);border-radius:5px;height:27px;padding:0 8px}.editor-grid{min-height:0;flex:1;display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--border);border-radius:8px;overflow:hidden}.editor-grid textarea{resize:none;border:0;border-right:1px solid var(--border);outline:none;background:var(--surface);color:var(--text);padding:18px;font:13px/1.8 Consolas,monospace}.preview{padding:18px;overflow:auto;background:var(--panel)}.preview-label{font-size:9px;letter-spacing:.15em;color:var(--muted);margin-bottom:12px}.preview pre{white-space:pre-wrap;font:13px/1.8 inherit;color:var(--text)}.editor-empty{height:100%;display:grid;place-items:center;align-content:center;text-align:center}.editor-empty strong{font-size:17px}.editor-empty p{color:var(--muted);font-size:12px}.editor-empty button{height:34px;border-radius:6px;padding:0 13px}.danger-text{color:#e56b6b!important}@media(max-width:900px){.workspace-body{grid-template-columns:210px 1fr}.editor-grid{grid-template-columns:1fr}.preview{display:none}}
</style>
